/**
 * DEPRECATED.
 * REDUX HAS BEEN MIGRATED TO UTILIZE THE REDUX TOOLKIT LIBRARY
 */

export const INITIALIZE_CART = "INITIALIZE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
